1541395840
Summertime
so there is a while loop that can handle null output, and one that can handle error output, but there isn't a way to easily handle output which can be nullable and can throw an error?

1541396252
andrewrk
Summertime, correct - not at the same time

1541396287
andrewrk
if and while support the same syntax with regards to optionals and error unions

1541396297
andrewrk
so you will probably have an outer while loop and an inner if

1541398378
Summertime


1541398675
Summertime
one thing that's kinda eating at me, is I've got multiple calls to stdout.write which can error, in slightly different scopes, `try` will push it up scopes, but how do I handle it before it hits main?

1541398721
andrewrk
Summertime, is this posix-only code? you might want to use args.nextPosix() instead of args.next()

1541398735
andrewrk
the posix only API does not require an allocator and cannot fail

1541398823
andrewrk
have a look at using `if` and `catch` with errors

1541399333
Summertime
m, still not quite putting it together mentally, like, I know I can catch on each write, I know I can use if to conditionally run code if its an noterror/error, but I'm not too sure what is the zigish? approach with this code, in other languages it'd be a trycatch, in zig, do I wrap the code in a function instead?

1541399399
Summertime
I think I could just really muck around with the panic handler and call it a day, but that seems a bit hackish

1541399421
andrewrk
are you looking to avoid `try` in main? if so why?

1541399453
andrewrk
or rather, a better question - what are you trying to accomplish?

1541399529
Summertime
if there is an error writing to stdout, I want at most the application to give an non-zero exit, and have zero output on stderr

1541399666
Summertime
I don't mind try in main, but I just want it to say and act exactly how I want if an error happens... I guess panic handler is the answer then?

1541399746
Summertime
oh, panic handler doesn't go if errors are returned from main?

1541399787
andrewrk
Summertime, that will happen in a release-fast build

1541399802
andrewrk
in release-fast returning an error from main just does exit(1)

1541399831
andrewrk


1541399852
andrewrk
ok my mistake - actually in release-fast mode it prints error: Foo

1541399885
andrewrk
if you want it to print nothing and do exit(1), I don't think you need to mess with the panic handler. I think you just want to have main do: main2() catch |err| exit(1)

1541399940
andrewrk
or, make the return value of main u8, and then `main2() catch return 1`

1541400133
Summertime
easy enough, thanks for the guidance!

1541400198
Summertime


1541412196
presiden
is there similar function like warn, but for stdout?

1541412234
presiden
something similar to printf?

1541422892
Hejsil
presiden,

1541424020
presiden
Hejsil: owh, I see

1541424057
presiden
Is the std documentation out there somewhere?

1541424099
Hejsil
Not yet:

1541424462
presiden
I see

1541430667
andrewrk
MajorLag, have a look at

1541430689
andrewrk
the master branch stuff is auto-updated now

1541439551
wilsonk
@andrewrk  Thanks for the dark theme for the ziglang documentation!!! :).  SOOOO much more readable and easy on the eyes!

1541440409
andrewrk
wilsonk, you're welcome

1541442699
Jenz
I want to read the contents of a file into a var. In github:ziglang/zig/examples/cat the program uses a buffer, [1024 * 5]u8, but how do I do it if I want variable length?

1541442724
andrewrk
Jenz, perhaps do you want std.io.readFileAlloc?

1541442781
andrewrk
this API is missing a parameter to set a maximum allowed file size - so be sure to use it only if the length of the file is not user input.

1541442813
Jenz
Thanks a ton andrewrk!

